project:
  type: website
  output-dir: docs

website:
  title: "Book Summaries"
  twitter-card: true
  open-graph: true
  favicon: favicon.ico
  site-url: "https://summaries.muthu.co"
  sidebar:
    style: "docked"
    search: true
  navbar:
    search: true
  page-navigation: true
  page-footer: 
    left: "Made with love using AI" 
    border: true

format:
  html:
    toc: true
    default-image: 'image.png'
    page-layout: article
    toc-location: "left"
    theme: none
      # light: litera 
      # dark: cyborg
    css: styles.css
    mermaid: 
      theme: neutral
    minimal: true
    include-after-body:
      - text: |
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3609399560636561" crossorigin="anonymous"></script>

