project:
  type: website
  output-dir: docs

website:
  title: "Book Summaries"
  description: Summaries of 1000+ greatest books
  twitter-card: true
  open-graph: true
  favicon: logo.png
  google-analytics: 
    tracking-id: 'G-Q0SHDCJVLL'
  site-url: "https://summaries.muthu.co"
  site-path: '/'
  navbar:
    logo: logo.png
    search: true
  sidebar:
    style: "docked"
    search: true
    contents: auto
  page-navigation: true
  page-footer: 
    left: "Made with Love and AI" 
    border: true
  bread-crumbs: false

format:
  html:
    default-image: 'image.png'
    page-layout: article
    theme: 
      light: litera 
      dark: cyborg
    css: styles.css
    mermaid: 
      theme: neutral
    minimal: true
    include-after-body:
      - text: |
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3609399560636561" crossorigin="anonymous"></script>

