project:
  type: website
  output-dir: docs

website:
  title: "Book Summaries"
  description: Access summaries of 1000+ self-help books, with actionable insights delivered in 15 minutes or less.
  twitter-card: true
  open-graph: true
  favicon: logo.png
  site-url: "https://summaries.muthu.co"
  navbar:
    logo: logo.png
    search: true
  sidebar:
    style: "docked"
    search: false
    contents: auto
  page-navigation: true
  page-footer: 
    left: "Powered by AI" 
    border: true
  bread-crumbs: false

format:
  html:
    toc: true
    default-image: 'image.png'
    page-layout: article
    toc-location: "left"
    theme: 
      light: litera 
      dark: cyborg
    css: styles.css
    mermaid: 
      theme: neutral
    minimal: true
    include-after-body:
      - text: |
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3609399560636561" crossorigin="anonymous"></script>

